### ISSUE TITLE
Hosting on gear

### ISSUE THREAD

**Issue by BenzionKlatzko** [ykoblick/shabbatcom#113]
There is a redundancy with the available to host setting. When clicking of the gear, it asks "can I host" but if you click on the bottom of the drop-down where it says "all my settings" it gives you that same option under "my role and status on Shabbat.com". That field I believe should be deleted. The bigger issue is that if that field exists, and you set it to "unavailable" when you go to the gear at the drop-down "can I host" and set it to available, it will revert back to unavailable because of the settings in the "all my settings page" that was set to unavailable.

**Comment by ykoblick** [comment]
No problem – will fix. The redundancy is based on evolving the settings locations and not removing the prev. section etc.

**Comment by ykoblick** [comment]
So - to be clear I will remove the hosting settings on the users 'settings' page. 

Really, that entire page is unnecessary since all the settings are covered in the 'gear dropdown' or profile settings. 

So the actual remedy is to remove the links to the page in the gear. That's all. 

Finally, I think that we should reference the hosting preferences when we add them to the edit profile section in the gear menu as well.
