### ISSUE TITLE
Keeping link in the Status update

### ISSUE THREAD

**Issue by BenzionKlatzko** [ykoblick/shabbatcom#15]
When posting a status update with a link, the preview of the website appears but the actual link disappears. This leads to very awkward sentences. For example, a person can post a status update that says "check out the website www.TorahAnytime.com you will be able to learn a whole lot of Torah" and it will remove words www.TorahAnytime.com, so that sentence will end up reading  "check out the website you will be able to learn a whole lot of Torah"

**Comment by ykoblick** [comment]
Got it. I need to normalize the display for this as there is different treatment for the app, site as well as the current feed and new timeline. Shouldn't be thought to do.

On Jul 17, 2016, at 11:52 AM, BenzionKlatzko <notifications@github.com<mailto:notifications@github.com>> wrote:


When posting a status update with a link, the preview of the website appears but the actual link disappears. This leads to very awkward sentences. For example, a person can post a status update that says "check out the website www.TorahAnytime.com<http://www.TorahAnytime.com> you will be able to learn a whole lot of Torah" and it will remove words www.TorahAnytime.com<http://www.TorahAnytime.com>, so that sentence will end up reading " "check out the website you will be able to learn a whole lot of Torah"

-
