### ISSUE TITLE
apparently, when changing a last name, it throws off the page url and causes an error

### ISSUE THREAD

**Issue by BenzionKlatzko** [ykoblick/shabbatcom#30]
Darling this happened twice. Once, when someone he was the Facebook login. It took them middle name instead of their last name, (they had three names), when I try to change their last name it yielded an error.

And just now, we changed someone's Maiden name, and then changed the address. When we can try to change them from a guest to a host it yielded an error as well.

http://www.shabbat.com/profile/hadassah.norman/

http://www.shabbat.com/pages/error.aspx?aspxerrorpath=/profile/hadassah.norman/

**Comment by ykoblick** [comment]
Darling?

I think fixed this yesterday but haven't posted the changes. Will check.

On Jul 18, 2016, at 9:53 PM, BenzionKlatzko <notifications@github.com<mailto:notifications@github.com>> wrote:


Darling this happened twice. Once, when someone he was the Facebook login. It took them middle name instead of their last name, (they had three names), when I try to change their last name it yielded an error.

And just now, we changed someone's Maiden name, and then changed the address. When we can try to change them from a guest to a host it yielded an error as well.

http://www.shabbat.com/profile/hadassah.norman/

http://www.shabbat.com/pages/error.aspx?aspxerrorpath=/profile/hadassah.norman/

**Comment by BenzionKlatzko** [comment]
A voice dictated it. Funny thing that voice dictation

**Comment by ykoblick** [comment]
This should be fixed. Will test locally
