### ISSUE TITLE
Post message on app slow

### ISSUE THREAD

**Issue by ykoblick** [ykoblick/shabbatcom#53]
Issue with trying to send a message hanging

**Comment by KodkodGates** [comment]
Are you sure ?

Trying to reply on Android is almost impossible.  Post button works only sometimes.

**Comment by ykoblick** [comment]
I need you to be a little more descriptive here.

Where is there a reply to button in the app?

The ‘post’ button in the app has been tested over and over on different android devices since our last android release with no latency issues. I may bee to know your device and android version. It may be related to your account in some way and possible corruption in your message records.

**Comment by ykoblick** [comment]
Check again - a user posted:

Also, in the android app, tapping on Post just adds another line into the msg & does not cause it to be sent.... can't send msgs fm my tablet... only from computer

**Comment by ykoblick** [comment]
Gal, I'm trying to work on solving this - today I received 2 complaints. You can help me by telling me where it's breaking down. First, to be clear, you are in a conversation in the app and you type a message and you tap the button 'send'. What happens? Does the spinner (loader) display that says sending. Is it just hanging there? Obviously, if you go to your message page you don't see the sent message. Meaning it's not some code after the message has been sent that is broken. Please confirm this much. It could be an issue server-side and not in the app itself

**Comment by KodkodGates** [comment]
Hi Yehudah
1. It just hanging there & Yossi Strum and I both tested this again and again last night.  Sending any messages, commenting works only after clicking the send button like over & over & over & over again (not exaggerating like may be 20-30 times sometimes.  There are times this is a non-issue.... It's very frustrating to not be able to send a message or comment after typing something & than losing it, if the button does not work.   
2. I do not think the problem is with android device & suspect there is an issue with back end code as the website is very slow today, loading the messaging feed & editing posts on a powerhouse laptop with a very quick connection.
